# Sub-workflow to pull from main repo and deploy to gh-pages branch
name: Deploy LHTP workshops site manually

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repo's gh-pages branch
      uses: actions/checkout@v2
      with:
        repository: 'epicodus/lhtp'
        ref: 'gh-pages'
        path: 'main-repo'

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Checkout gh-pages branch
      run: |
        git init
        git checkout -b gh-pages

    - name: ls ./
      run: ls ./

    - name: ls ./main-repo/
      run: ls ./main-repo/

    - name: ls ./main-repo/all-builds/
      run: ls ./main-repo/all-builds/

    - name: Copy directory
      run: cp -R ./main-repo/all-builds/build-workshops .

    - name: Replace CNAME
      run: echo "workshops.learnhowtoprogram.com" > CNAME

    - name: Delete main-repo directory
      run: rm -rf ./main-repo

    - name: Commit & Push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy to gh-pages"
        git push origin +gh-pages
