# Sub-workflow to pull from main repo and deploy to gh-pages branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repo's gh-pages branch
      uses: actions/checkout@v2
      with:
        repository: 'epicodus/lhtp'
        ref: 'gh-pages'
        path: 'main-repo'

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Copy directory
      run: cp -R ./main-repo/all-builds/workshops .

    - name: Checkout gh-pages branch
      run: |
        git fetch origin gh-pages
        git checkout gh-pages

    - name: Commit & Push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy to gh-pages"
        git push origin gh-pages
