# Sub-workflow to pull from main repo and deploy to gh-pages branch
name: Manually deploy LHTP workshops site

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: 'gh-pages'

    - name: Clear gh-pages branch
      run: rm -rf *

    - name: Checkout main repo's gh-pages branch
      uses: actions/checkout@v3
      with:
        repository: 'epicodus/lhtp'
        ref: 'gh-pages'
        path: 'main-repo'

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Copy directory
      run: cp -R ./main-repo/build-workshops/* .

    - name: Replace CNAME
      run: echo "workshops.learnhowtoprogram.com" > CNAME

    - name: Delete main-repo directory
      run: rm -rf ./main-repo

    - name: Set default origin
      run: git remote set-url origin https://github.com/epicodus/lhtp-workshops.git

    - name: Commit & Push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Deploy to gh-pages"
        git push origin +gh-pages
